[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pnpm install --prefer-offline"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
