[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm@10.4.1 && pnpm install && pnpm run build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
